### ISSUE TITLE
support for in, not in operators

### ISSUE THREAD

**Issue by mkingbe** [dabernathy89/vue-query-builder#11]
Hello,

Do you plan do add support for in, not in operator ?

**Comment by dabernathy89** [comment]
@mkingbe - you can provide custom operators pretty easily. For any of the built-in rule types (e.g. `text`, `radio`, etc) you can override the defaults, including the operators.

You can see a basic example of this on the documentation page:

https://dabernathy89.github.io/vue-query-builder/

under "Basic Demo Source", you can see a rule with custom operators:

```
        {
          type: "select",
          id: 'select',
          label: 'Color',
          operators: ['=', '<>'],
          choices: [] // Removed for brevity
        },
```
