### ISSUE TITLE
Q: QueryBuilderGroup  rule selector blank and "selectedRule" undefined after rules changed

### ISSUE THREAD

**Issue by terrygogo** [dabernathy89/vue-query-builder#18]
When I changed rules  after once vue-query-builder created,  all the rules of QueryBuilderGroup updated well as I assigned by program,  but rule select label is remain blank and "selectedRule" is also undifine. Only after I click it, It have a value.  

I hope to get idea If I want to display first rule in selector even I changed the rules dynamically .

**Comment by dabernathy89** [comment]
Sorry this never got any activity. Had a baby in April so things got quite busy 😬

If you're able to reproduce this issue for me using Code Sand Box (https://codesandbox.io) or something similar, please do and share here. If I don't here back I'll assume I waited too long to respond and close the issue for inactivity (my bad).

**Comment by dabernathy89** [comment]
This issue should be fixed now.
