### ISSUE TITLE
Group in group

### ISSUE THREAD

**Issue by kszymukowicz** [dabernathy89/vue-query-builder#19]
hi
First of all - tnx for nice plugin!
I have question: do you plan to have nested groups ?

**Comment by abloch** [comment]
nested groups are already possible in vue-query-builder. 
for some reason awkward reason, the [demo](https://dabernathy89.github.io/vue-query-builder/) limits `maxDepth` to 2 and prevents you from experiencing with this.

**Comment by dabernathy89** [comment]
Yep, @abloch is correct. Sorry i've been a little inactive in this repo - just had a baby a few weeks ago! Hope to get some more work done in a couple weeks once things settle down here.
