### ISSUE TITLE
Date  as custom component not working

### ISSUE THREAD

**Issue by amsanket22** [dabernathy89/vue-query-builder#26]
How to add date as custom component? I have added it as a custom-component but it does not work it shows blank object? please guide

**Comment by dabernathy89** [comment]
@amsanket22 can you spin up an example (https://codesandbox.io/ is a good option) to show me what you've tried so far?

**Comment by amsanket22** [comment]
Thank you for your reply but that issue has been solved. that component was not having v-model.

**Comment by dabernathy89** [comment]
Gotcha - glad you figured it out!
