### ISSUE TITLE
Reset the Query Builder

### ISSUE THREAD

**Issue by paulheijman** [dabernathy89/vue-query-builder#30]
Hi,

Is it possible to reset the query builder? I tried setting the v-model to '{}', but this doesn't update the component...

**Comment by beargie** [comment]
I use this method to clear the query:
`onReset() {
this.query = 'logicalOperator=All';
$(".children").empty();
this.hasQuery = false;
},`

Make sure I add hasQuery by default in my vue data() function:
`hasQuery: false,`

And then my reset button below the query builder:
`<button type="button" @click="onReset()" class="btn btn-secondary btn-sm" :disabled="!hasQuery">Reset</button>`

**Comment by paulheijman** [comment]
Thanks beargie, this sent me on the right track.

In the end I'm using this:

`this.$refs.vqb.query.children = [];`

where vqb is a ref to the component.
