### ISSUE TITLE
Where we can change the JSON data structure?

### ISSUE THREAD

**Issue by jelordreygulle** [dabernathy89/vue-query-builder#36]
Where can we change the json data structure? as for now what i have so far is the example below but what if i changed the structure like for example I have question where in question contains answers and and then answers contains products. something like that.

#the structure that i want , something like this  , changing the generated json structure where can we modity that from you're builder?

[

    store1: [
    {
        question1: [
            {
                answer1: [
                    product1,
                    product2,
                    product3,
                ]
            },
            {
                answer2: [
                    product1,
                    product2,
                    product3,
                ]
            }

        ]
    }]
]

#what i have so far
{
  "logicalOperator": "All",
  "children": [
    {
      "type": "query-builder-rule",
      "query": {
        "rule": "question",
        "selectedOperator": "equals",
        "selectedOperand": "Question",
        "value": "What is my name?"
      }
    },
    {
      "type": "query-builder-rule",
      "query": {
        "rule": "answer",
        "selectedOperator": "equals",
        "selectedOperand": "Answer",
        "value": "Test"
      }
    },
    {
      "type": "query-builder-rule",
      "query": {
        "rule": "multi-select-field",
        "selectedOperator": "=",
        "selectedOperand": "Products",
        "value": [
          "Red",
          "Orange",
          "Yellow",
          "Green"
        ]
      }
    }
  ]
}

**Comment by jelordreygulle** [comment]
Yes Sir , I am talking about changing the json structure of the components output.

**Comment by dabernathy89** [comment]
Quick aside: to output a code block in Github comments, make sure to use triple backticks:

\`\`\`
Code here
\`\`\`

Renders as:

```
Code here
```

As to the question: the easiest way to do what you need is to create a `computed` property in your Vue instance that reads the Query Builder output and renders some new data from it. There's now way to alter the format of the generated JSON.
