### ISSUE TITLE
limit the number of (Add Rule and Add Group)

### ISSUE THREAD

**Issue by mprabu0104** [dabernathy89/vue-query-builder#44]
Can we able to limit the number of children to add ( ie query-builder-group and query-builder-rule)

**Comment by dabernathy89** [comment]
Hey @mprabu0104 - there's no built-in support for this, but it should be achievable if you use a custom template:

https://dabernathy89.github.io/vue-query-builder/custom-templates.html#setting-up-your-vue-instance
