### ISSUE TITLE
Slots

### ISSUE THREAD

**Issue by amellini** [dabernathy89/vue-query-builder#48]
It will be nice to have some slot to personalize a bit the main UI , some example:
- MatchType panel (add or remove some butto "Apply" or "Reset")
- AddRule / Add Group section for a better personalization
- Panel footer (as before)

**Comment by dabernathy89** [comment]
@amellini sorry this took so long. I tried for a long time to figure out how to take advantage of slots to let people customize the query builder, but in the end they just weren't flexible enough. My solution was just to turn the query builder into a renderless component (with a default very similar to before). It is more work on the end user but provides much more ability to customize everything.

You can see the docs (still WIP) on that here:

https://dabernathy89.github.io/vue-query-builder/custom-templates.html#setting-up-your-vue-instance

**Comment by amellini** [comment]
Ok, thanks I'll take a look at your solution.
I would have imagined component of the control, for example:
- QueryBuilderHeader (a template-based header with a slot)
- QueryBuilderRuleGroup: same as before with three grouped components
- QueryBuilderRule: for the actual rule

Thank you again
