### ISSUE TITLE
ReferenceError: _h is not defined

### ISSUE THREAD

**Issue by aligundogdu** [dabernathy89/vue-query-builder#5]
My Vue versiyon is 2.2.1 

![screenshot_24](https://cloud.githubusercontent.com/assets/683384/23462987/9c15a934-fe98-11e6-890e-b8145151167f.png)

i import like this: 

```
import builder from 'vue-query-builder';
Vue.component('vue-query-builder',builder);

```

and i use like this :

```
                <vue-query-builder
                        :rules="myRules"
                        :maxDepth="2"
                ></vue-query-builder>
```

how can i fix it ?

thanks.

**Comment by dabernathy89** [comment]
Sorry it has taken me so long to address this. Did you have any luck getting it working? I haven't run across this issue myself yet.

**Comment by aligundogdu** [comment]
Hi,

no its not working :(

**Comment by dabernathy89** [comment]
I've updated the component to use Vue CLI 3 under the hood. If this issue is still happening for anyone, please ping me to reopen.
