### ISSUE TITLE
Is there a interface to overwrite the operators to like "=, !=, etc"?

### ISSUE THREAD

**Issue by ytl18** [dabernathy89/vue-query-builder#51]

**Comment by andreas83** [comment]
not sure if i understand you correctly.
there is a option for operators (bzw: a nice feature would be having label and value  )
  ```
rules:[{
  type: "text",
  id: "key",
  label: "Key",
  operators : ['=', '<', '>', '!=','in']
}]
```

**Comment by dabernathy89** [comment]
@andreas83 is correct - more detail here:

https://dabernathy89.github.io/vue-query-builder/configuration.html#rules

I'll see about adding support for labels & values on the operators. I don't see any reason that couldn't happen.

**Comment by andreas83** [comment]
@dabernathy89 awesome, thanks
